name:                hs-rss-al-retposxto
version:             0.1.2.0
github:              "ebrulato/hs-rss-al-retposxto"
license:             BSD3
author:              "Eric Brulatout"
maintainer:          "eric.brulatout@gmail.com"
copyright:           "ebr2020"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ebrulato/hs-rss-al-retposxto#readme>


dependencies:
- base >= 4.7 && < 5
- network >= 2.4 && < 3.0

library:
  source-dirs:
      src
  dependencies:
    - lens
    - http-client
    - wreq
    - bytestring
    - html-parse
    - text
    - url
    - JuicyPixels
    - JuicyPixels-extra
    - Color
    - base64
    - smtp-mail
    - mime-mail
    - aeson
    - mtl
    - directory

executables:
  hs-rss-al-retposxto-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-rss-al-retposxto
    - lens
    - http-client
    - wreq
    - bytestring
    - html-parse
    - text
    - url
    - JuicyPixels
    - JuicyPixels-extra
    - Color
    - base64
    - smtp-mail
    - mime-mail
    - aeson
    - mtl
    - directory

tests:
  hs-rss-al-retposxto-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-rss-al-retposxto
